name: Our first python CI  

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs: 
  My-first-CI: # job which will build and test the project
    runs-on: ubuntu-latest  # specifies virtual host environment to run the job

    steps:
    - uses: actions/checkout@v3  # checks out repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  
        pip install -r requirements.txt

    - name: Lint with Ruff  # Use Ruff to lint the code
      run: |
        ruff check ./src --output-format=github  

    - name: Test with pytest
      run: |  
        pytest  
